# Generated by Django 5.0.1 on 2025-10-30 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fornecedor', 'Fornecedor'), ('faturado', 'Faturado')], max_length=45)),
                ('razao_social', models.CharField(max_length=150)),
                ('fantasia', models.CharField(blank=True, max_length=150, null=True)),
                ('documento', models.CharField(max_length=45, unique=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('a pagar', 'A Pagar'), ('a receber', 'A Receber')], default='a pagar', max_length=45)),
                ('numero_nota_fiscal', models.CharField(max_length=45, unique=True)),
                ('data_emissao', models.DateField()),
                ('descricao', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('classificacoes', models.ManyToManyField(db_table='MovimentoContas_Classificacao', to='core.classification')),
                ('faturado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_faturados', to='core.person')),
                ('fornecedor_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.person')),
            ],
            options={
                'verbose_name': 'Account Transaction',
                'verbose_name_plural': 'Account Transactions',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=45)),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status_parcela', models.CharField(default='aberta', max_length=45)),
                ('account_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.accounttransaction')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
            },
        ),
    ]
