# Generated by Django 5.0.1 on 2025-11-07 18:39

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='accounttransaction',
            name='descricao_embedding',
            field=pgvector.django.vector.VectorField(dimensions=768, null=True),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['descricao_embedding'], m=16, name='idx_desc_embedding_hnsw', opclasses=['vector_l2_ops']),
        ),
    ]
