# Generated by Django 5.0.1 on 2025-10-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45),
        ),
        migrations.AlterField(
            model_name='person',
            name='tipo',
            field=models.CharField(choices=[('fornecedor', 'Fornecedor'), ('faturado', 'Faturado')], default=2, max_length=45),
            preserve_default=False,
        ),
    ]
