# Generated by Django 5.0.1 on 2025-10-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_person_status_alter_person_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='classificacoes',
            field=models.ManyToManyField(db_table='MovimentoContas_Classificacao', to='models.classification'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='numero_nota_fiscal',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='tipo',
            field=models.CharField(choices=[('a pagar', 'A Pagar'), ('a receber', 'A Receber')], default='a pagar', max_length=45),
        ),
    ]
