# Generated by Django 5.0.1 on 2025-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_alter_accounttransaction_classificacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=45),
        ),
    ]
